name: CI
on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build code
      run: cargo build --workspace --examples

  test:
    needs: [build]
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # intel
          macos-13,
          # arm
          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Test code
      run: cargo test --release -- --nocapture

  coverage:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master')
    needs: [test]
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Cinstrument-coverage
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: llvm-tools
    - run: cargo install grcov
    - run: cargo build --verbose
    - name: Run tests
      run: LLVM_PROFILE_FILE="stuck-%p-%m.profraw" cargo test --verbose -- --nocapture
    - name: Generate coverage report
      run: grcov $(find . -name "stuck-*.profraw" -print) --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        verbose: true

  lint:
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: clippy
    - name: Lint code
      run: cargo clippy --no-deps -- -D clippy::all

  release:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: install cargo-workspaces to publish workspace
      run: cargo install cargo-workspaces
    - name: publish crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo workspaces publish --from-git
